spring:
  application:
    name: educacao-continuada-gamificada
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:h2}
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
